### PR TITLE
BUG: Fix PR warning logic

### PR DESCRIPTION
**Pull request by pllim**
Address comment from @bsipocz from astropy/astropy#12133

### CODE REVIEW

**Comment by pllim** [comment]
With this patch:

```
Checking 10134 with labels ['timeseries']
-> MARK PR 10134 as stale with "Close?" label
-> OK PR 10134 (already warned), time_since_last_commit=43901441.548645735, time_since_last_warning=30448815.548645735
Checking 9870 with labels ['table']
-> MARK PR 9870 as stale with "Close?" label
-> OK PR 9870 (already warned), time_since_last_commit=42062180.548645735, time_since_last_warning=28375199.548645735
Checking 9856 with labels ['Bug', 'coordinates']
-> MARK PR 9856 as stale with "Close?" label
-> WARNING PR 9856, time_since_last_commit=36092704.548645735, time_since_last_warning=38224776.548645735
```

Is this better?

**Comment by bsipocz** [comment]
Yes, much better. One more tiny thing, could you maybe convert the times to a more useful unit, e.g, days?

**Comment by pllim** [comment]
> e.g, days?

Yes, that makes sense. I'll come back to this tomorrow. 😸

**Comment by pllim** [comment]
What about now?

```
Checking 11397 with labels ['units', 'Bug', 'modeling']
-> OK PR 11397 (not stale), last commit was 2021-08-03 21:55:19+00:00
```

```
Checking 11363 with labels ['nddata']
-> MARK PR 11363 as stale with "Close?" label, last commit was 2021-03-03 16:10:15+00:00
-> WARNING PR 11363, no warning ever issued
```

```
-> MARK PR 10263 as stale with "Close?" label, last commit was 2020-05-02 00:43:58+00:00
-> OK PR 10263 (already warned), 10 months since last warning
```

```
Checking 9856 with labels ['Bug', 'coordinates']
-> MARK PR 9856 as stale with "Close?" label, last commit was 2020-07-10 00:16:28+00:00
-> WARNING PR 9856, warning issued on 2020-06-15 08:01:56+00:00 no longer applicable
```

```
Checking 8723 with labels ['io.votable', 'coordinates', 'keep-open']
-> PROTECTED by keep-open, skipping and removing "Close?" label if it exists
```

**Comment by bsipocz** [comment]
Ohh, TIL `naturaldelta` and quite like it :)

**Review by bsipocz — APPROVED** [review]
Superb, :shipit: !

**Comment by pllim** [comment]
OK let's look at the real dry run tomorrow... 🤞

**Pull request merged**
